### ISSUE TITLE
Correctness Of Algorithm

### ISSUE THREAD

**Issue by ROOPKANTH-KURRA** [scottjulian/C4.5#2]
I think this source code is giving same answers or final outputs for any data set given.This made me suspect correctness of algorithm.Please once again verify and correct it if anything is wrong and sorry if I am wrong.

**Comment by scottjulian** [comment]
I no longer support this project. If you can prove it is wrong and have a fix to submit, I will review it.

**Comment by ROOPKANTH-KURRA** [comment]
Thanks for the response mate.I will try to check out if there are any mistakes and if any I will send a pull request.Thanks again.
